// const { createClient } = require('@supabase/supabase-js');
// const fs = require('fs');
// require('dotenv').config();

// // Initialize Supabase Client
// const supabaseUrl = process.env.SUPABASE_URL;
// const supabaseKey = process.env.SUPABASE_KEY;
// const supabase = createClient(supabaseUrl, supabaseKey);

// // Load the clean data generated by Gemini
// const cleanData = JSON.parse(fs.readFileSync('karachi_clean.json', 'utf8'));

// async function seedDatabase() {
//     console.log(`📡 Mapping data to teammate's schema for ${cleanData.length} records...`);

//     // Map your clean JSON array into your teammate's exact table structure
//     const dbRows = cleanData.map((item, index) => {
//         // Creating a standard PostGIS geometry point string: 'POINT(lng lat)'
//         const wktGeometry = `POINT(${item.longitude} ${item.latitude})`;
        
//         return {
//             osm_id: 1000000 + index, // Dummy unique OSM ID for hackathon fallback
//             name: item.name, 
//             name_clean: item.name, // Gemini cleaned version
//             alternative_names: item.keywords.join(', '), // Converts array to comma-separated text
//             category: item.amenity,
//             geometry: wktGeometry, // PostGIS compliant point
//             city: 'Karachi',
//             popularity_score: 0.0,
//             tags: {}, // Empty JSONB object to satisfy the column structure
//         };
//     });

//     console.log(`🚀 Uploading to table 'pois'...`);

//     const { data, error } = await supabase
//         .from('pois') // Targeting your teammate's table name
//         .insert(dbRows);

//     if (error) {
//         console.error('❌ Error seeding data:', error);
//     } else {
//         console.log('🏁 Success! All cleaned POIs match the team schema and are live in Supabase.');
//     }
// }

// seedDatabase();


const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
require('dotenv').config();

// 1. Initialize Supabase Client using variables from your .env file
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

// 2. Load the clean data generated by Gemini
const cleanData = JSON.parse(fs.readFileSync('karachi_clean.json', 'utf8'));

async function seedDatabase() {
    console.log(`📡 Re-formatting data for RPC pipeline...`);

    // 3. Map the fields to clean numbers and strings so the PostgreSQL function can read them easily
    const payload = cleanData.map((item, index) => ({
        osm_id: 1000000 + index,
        name: item.name,
        name_clean: item.name, 
        alternative_names: item.keywords.join(', '),
        category: item.amenity,
        longitude: item.longitude, // Sending raw floats, letting SQL convert to PostGIS geometry
        latitude: item.latitude,
        city: 'Karachi',
        popularity_score: 0.0,
        tags: {}
    }));

    console.log(`🚀 Executing RPC function 'insert_clean_pois' for ${payload.length} records...`);

    // 4. Call the remote procedure function directly to bypass PostgREST API string parsing issues
    const { data, error } = await supabase.rpc('insert_clean_pois', { data: payload });

    if (error) {
        console.error('❌ Error seeding data via RPC:', error);
        console.log('💡 Tip: Make sure your teammate created the "insert_clean_pois" function in the Supabase SQL editor.');
    } else {
        console.log('🏁 Success! The RPC route worked perfectly. Your clean POI data is now live in your teammate\'s Supabase table!');
    }
}

seedDatabase();